FROM resin/%%RESIN_MACHINE_NAME%%-python

#switch on systemd init system in container
ENV INITSYSTEM on

RUN pip install RPi.GPIO firebase-admin google-cloud-firestore

COPY . /usr/src/app
WORKDIR /usr/src/app

CMD ["python", "script.py"]
