FROM resin/%%RESIN_MACHINE_NAME%%-python

#switch on systemd init system in container
ENV INITSYSTEM on

# pip install python deps from requirements.txt
# For caching until requirements.txt changes
# COPY ./requirements.txt /requirements.txt
RUN RPi.GPIO firebase-admin google-cloud-firestore

COPY . /usr/src/app
WORKDIR /usr/src/app

CMD ["python", "script.py"]
